package soura;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author L41
 */
public class goalscorer extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public goalscorer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        a13 = new javax.swing.JTextField();
        a14 = new javax.swing.JTextField();
        a15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();
        b7 = new javax.swing.JTextField();
        b8 = new javax.swing.JTextField();
        b9 = new javax.swing.JTextField();
        b10 = new javax.swing.JTextField();
        b12 = new javax.swing.JTextField();
        b11 = new javax.swing.JTextField();
        b13 = new javax.swing.JTextField();
        b14 = new javax.swing.JTextField();
        b15 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        c5 = new javax.swing.JTextField();
        c6 = new javax.swing.JTextField();
        c7 = new javax.swing.JTextField();
        c8 = new javax.swing.JTextField();
        c9 = new javax.swing.JTextField();
        c10 = new javax.swing.JTextField();
        c12 = new javax.swing.JTextField();
        c11 = new javax.swing.JTextField();
        c13 = new javax.swing.JTextField();
        c14 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        c15 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        d4 = new javax.swing.JTextField();
        d5 = new javax.swing.JTextField();
        d6 = new javax.swing.JTextField();
        d7 = new javax.swing.JTextField();
        d8 = new javax.swing.JTextField();
        d9 = new javax.swing.JTextField();
        d10 = new javax.swing.JTextField();
        d12 = new javax.swing.JTextField();
        d11 = new javax.swing.JTextField();
        d13 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        d14 = new javax.swing.JTextField();
        d15 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        e2 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        e4 = new javax.swing.JTextField();
        e5 = new javax.swing.JTextField();
        e6 = new javax.swing.JTextField();
        e7 = new javax.swing.JTextField();
        e8 = new javax.swing.JTextField();
        e9 = new javax.swing.JTextField();
        e10 = new javax.swing.JTextField();
        e12 = new javax.swing.JTextField();
        e11 = new javax.swing.JTextField();
        e13 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        e14 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        e15 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(920, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FC Barcelona");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 26, 133, 48));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MARC ANDRE TER STEGEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GERRAD PIQUE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IVAN RAKITIC");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SERGIO BUSQUETS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));

        jLabel6.setText("LIONEL MESSI ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 295, -1, -1));

        jLabel7.setText("OUSAMANNE DEMBELE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        jLabel8.setText("NETO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 373, -1, -1));

        jLabel9.setText("CLEMET LENGLET");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 411, -1, -1));

        jLabel10.setText("ANTOINE GRIEZMAN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 449, -1, -1));

        jLabel11.setText("ARTHUR MELO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel12.setText("LUIS SUAREZ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 257, -1, -1));

        jLabel13.setText("JORDI ALBA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 487, -1, -1));

        jLabel14.setText("SERGIO ROBERTO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 525, -1, -1));

        jLabel15.setText("FRENKIE DE JONG");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 556, -1, -1));

        jLabel16.setText("ARTURO VIDAL");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 596, -1, -1));

        a1.setEditable(false);
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 80, 29, -1));

        a2.setEditable(false);
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 118, 29, -1));

        a3.setEditable(false);
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 156, 29, -1));

        a4.setEditable(false);
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 186, 29, -1));

        a5.setEditable(false);
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 217, 29, -1));

        a6.setEditable(false);
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 254, 29, -1));

        a7.setEditable(false);
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 292, 29, -1));

        a8.setEditable(false);
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 332, 29, -1));

        a9.setEditable(false);
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 370, 29, -1));

        a10.setEditable(false);
        getContentPane().add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 408, 29, -1));

        a11.setEditable(false);
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 484, 29, -1));

        a12.setEditable(false);
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 446, 29, -1));

        a13.setEditable(false);
        getContentPane().add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 522, 29, -1));

        a14.setEditable(false);
        getContentPane().add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 553, 29, -1));

        a15.setEditable(false);
        getContentPane().add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 593, 29, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("KEYLOR NAVAS");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 83, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("DANI CARVAJAL");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 121, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SERGIO RAMOS");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 159, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("RAPHAEL VARANE");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 189, -1, -1));

        jLabel22.setText("KARIM BENZEMA");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 220, -1, -1));

        jLabel23.setText("TONI KROOS");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 257, -1, -1));

        jLabel24.setText("LUKA MODRIC");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 295, -1, -1));

        jLabel25.setText("GARETH BALE");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 335, -1, -1));

        jLabel26.setText("MARCELO VIERRA");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 373, -1, -1));

        jLabel27.setText("THIBAUT COURTOIS");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 411, -1, -1));

        jLabel28.setText("LUCAS VAZQUEZ");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 449, -1, -1));

        jLabel29.setText("LUKA JOVIC");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 487, -1, -1));

        jLabel30.setText("MARCO ASENSIO");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 525, -1, -1));

        jLabel31.setText("VINICIUS JUNIOR");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 556, -1, -1));

        jLabel32.setText("EDEN HAZARD");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 596, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Real Madrid C.F.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 43, 102, -1));

        b3.setEditable(false);
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 156, 29, -1));

        b4.setEditable(false);
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 186, 29, -1));

        b5.setEditable(false);
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 217, 29, -1));

        b6.setEditable(false);
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 254, 29, -1));

        b7.setEditable(false);
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 292, 29, -1));

        b8.setEditable(false);
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 332, 29, -1));

        b9.setEditable(false);
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 370, 29, -1));

        b10.setEditable(false);
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 408, 29, -1));

        b12.setEditable(false);
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 484, 29, -1));

        b11.setEditable(false);
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 446, 29, -1));

        b13.setEditable(false);
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 522, 29, -1));

        b14.setEditable(false);
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 553, 29, -1));

        b15.setEditable(false);
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 593, 29, -1));

        b1.setEditable(false);
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 80, 29, -1));

        b2.setEditable(false);
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 118, 29, -1));

        jLabel33.setText("THOMAS LEMAR");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 295, -1, -1));

        jLabel34.setText("RENAN LODI");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 335, -1, -1));

        jLabel35.setText("JAN OBLAK");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 373, -1, -1));

        jLabel36.setText("MARCOS LLORENTE");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 411, -1, -1));

        jLabel37.setText("KOKE");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 449, -1, -1));

        jLabel38.setText("ALVARO MORATA");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 220, -1, -1));

        jLabel39.setText("ANGEL CORREA");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 257, -1, -1));

        jLabel40.setText("DIEGO COSTA");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 487, -1, -1));

        c2.setEditable(false);
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 118, 29, -1));

        c3.setEditable(false);
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 156, 29, -1));

        c4.setEditable(false);
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 186, 29, -1));

        c5.setEditable(false);
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 217, 29, -1));

        c6.setEditable(false);
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 254, 29, -1));

        c7.setEditable(false);
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 292, 29, -1));

        c8.setEditable(false);
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 332, 29, -1));

        c9.setEditable(false);
        getContentPane().add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 29, -1));

        c10.setEditable(false);
        getContentPane().add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 408, 29, -1));

        c12.setEditable(false);
        getContentPane().add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 484, 29, -1));

        c11.setEditable(false);
        getContentPane().add(c11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 446, 29, -1));

        c13.setEditable(false);
        getContentPane().add(c13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 522, 29, -1));

        c14.setEditable(false);
        getContentPane().add(c14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 553, 29, -1));

        jLabel41.setText("VITOLO");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 525, -1, -1));

        jLabel42.setText("MARIO HERMOSO");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 556, -1, -1));

        c1.setEditable(false);
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 29, -1));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Atletico Madrid");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 26, 133, 48));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("ANTONIO ADAN");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 83, -1, -1));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("THOMAS PARTEY");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 121, -1, -1));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("JOAO FELIX");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 159, -1, -1));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("SAUL NIGUEZ");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 189, -1, -1));

        jLabel48.setText("KIERAN TRIPPIER");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 596, -1, -1));

        c15.setEditable(false);
        getContentPane().add(c15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 593, 29, -1));

        jLabel49.setText("ALEIX VIDAL");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 295, -1, -1));

        jLabel50.setText("ANDRE SILVA");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 335, -1, -1));

        jLabel51.setText("NOLITO");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 373, -1, -1));

        jLabel52.setText("JESUS NAVAS");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 411, -1, -1));

        jLabel53.setText("JUAN SORIANO");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 449, -1, -1));

        jLabel54.setText("DANIEL CARRICO");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 220, -1, -1));

        jLabel55.setText("EVER BANEGA");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 257, -1, -1));

        jLabel56.setText("ESCUDERO");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 487, -1, -1));

        d2.setEditable(false);
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 118, 29, -1));

        d3.setEditable(false);
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 156, 29, -1));

        d4.setEditable(false);
        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 186, 29, -1));

        d5.setEditable(false);
        getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 217, 29, -1));

        d6.setEditable(false);
        getContentPane().add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 254, 29, -1));

        d7.setEditable(false);
        getContentPane().add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 292, 29, -1));

        d8.setEditable(false);
        getContentPane().add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 332, 29, -1));

        d9.setEditable(false);
        getContentPane().add(d9, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 370, 29, -1));

        d10.setEditable(false);
        getContentPane().add(d10, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 408, 29, -1));

        d12.setEditable(false);
        getContentPane().add(d12, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 484, 29, -1));

        d11.setEditable(false);
        getContentPane().add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 446, 29, -1));

        d13.setEditable(false);
        getContentPane().add(d13, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 522, 29, -1));

        jLabel57.setText("ROQUE MESA ");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 525, -1, -1));

        d1.setEditable(false);
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 80, 29, -1));

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Sevilla FC");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 26, 133, 48));

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("TOMAS VACILIK");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 83, -1, -1));

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("SERGI GOMEZ");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 121, -1, -1));

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("SIMON KJAER");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 159, -1, -1));

        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("IBRAHIM AMADOU");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 189, -1, -1));

        jLabel63.setText("QUINCY PROMES");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 556, -1, -1));

        d14.setEditable(false);
        getContentPane().add(d14, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 553, 29, -1));

        d15.setEditable(false);
        getContentPane().add(d15, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 593, 29, -1));

        jLabel64.setText("BEN YEDDER");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 596, -1, -1));

        jLabel65.setText("DANIEL PAREJO");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 295, -1, -1));

        jLabel66.setText("CARLOS SOLER");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 335, -1, -1));

        jLabel67.setText("GONCALO GUEDES");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 373, -1, -1));

        jLabel68.setText("ALVARO MEDRAN");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 411, -1, -1));

        jLabel69.setText("RODRIGO");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 449, -1, -1));

        jLabel70.setText("JOSE GAYA");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 220, -1, -1));

        jLabel71.setText("DANIEL WASS");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 257, -1, -1));

        jLabel72.setText("MAXI GOMEZ");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 487, -1, -1));

        e2.setEditable(false);
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 118, 29, -1));

        e3.setEditable(false);
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 156, 29, -1));

        e4.setEditable(false);
        getContentPane().add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 186, 29, -1));

        e5.setEditable(false);
        getContentPane().add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 217, 29, -1));

        e6.setEditable(false);
        getContentPane().add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 254, 29, -1));

        e7.setEditable(false);
        getContentPane().add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 292, 29, -1));

        e8.setEditable(false);
        getContentPane().add(e8, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 332, 29, -1));

        e9.setEditable(false);
        getContentPane().add(e9, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 370, 29, -1));

        e10.setEditable(false);
        getContentPane().add(e10, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 408, 29, -1));

        e12.setEditable(false);
        getContentPane().add(e12, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 484, 29, -1));

        e11.setEditable(false);
        getContentPane().add(e11, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 446, 29, -1));

        e13.setEditable(false);
        getContentPane().add(e13, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 522, 29, -1));

        e1.setEditable(false);
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 80, 29, -1));

        jLabel73.setBackground(new java.awt.Color(255, 255, 255));
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Valencia CF");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 26, 133, 48));

        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("JAUME DOMENECH");
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 83, -1, -1));

        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("JASPER CILLESSEN");
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 121, -1, -1));

        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("GABRIEL PAULISTA");
        getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 159, -1, -1));

        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("SALVA RUIZ");
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 189, -1, -1));

        jLabel78.setText("FERRAN TORRES");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 556, -1, -1));

        jLabel79.setText("KEVIN GAMEIRO");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 525, -1, -1));

        e14.setEditable(false);
        getContentPane().add(e14, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 553, 29, -1));

        jLabel80.setText("LEE KANG-IN");
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 596, -1, -1));

        e15.setEditable(false);
        getContentPane().add(e15, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 593, 29, -1));

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soura/im1.jpg"))); // NOI18N
        jLabel81.setText("jLabel81");
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 try
        {
             Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project12","root","123456");
            Statement stmt=con.createStatement();
             String str1="select count(pname) from PLAYERS  Where PNAME='MARC ANDRE TER STEGEN' ";
            
             ResultSet rs1=stmt.executeQuery(str1);
             if(rs1.next())
       {
       int R=rs1.getInt("count(pname)");
       a1.setText(""+R);
       }
        
              String str2="select count(pname) from players where pname='GERRAD PIQUE' ";
            
             ResultSet rs2=stmt.executeQuery(str2);
             if(rs2.next())
       {
       int R=rs2.getInt("count(pname)");
       a2.setText(""+R);
        }
                      String str3="select count(pname) from players where pname='IVAN RAKITIC'";
            
             ResultSet rs3=stmt.executeQuery(str3);
             if(rs3.next())
       {
       int R=rs3.getInt("count(pname)");
       a3.setText(""+R);
        }
                    String str4="select count(pname) from players where pname='SERGIO BUSQUETS'";
            
             ResultSet rs4=stmt.executeQuery(str4);
             if(rs4.next())
       {
       int R=rs4.getInt("count(pname)");
       a4.setText(""+R);
        }
                   String str5="select count(pname) from players where pname='ARTHUR MELO'";
            
             ResultSet rs5=stmt.executeQuery(str5);
             if(rs5.next())
       {
       int R=rs5.getInt("count(pname)");
       a5.setText(""+R);
        }
             String str6="select count(pname) from players where pname='LUIS SUAREZ'";
            
             ResultSet rs6=stmt.executeQuery(str6);
             if(rs6.next())
       {
       int R=rs6.getInt("count(pname)");
       a6.setText(""+R);
        }
             String str7="select count(pname) from players where pname='LIONEL MESSI '";
            
             ResultSet rs7=stmt.executeQuery(str7);
             if(rs7.next())
       {
       int R=rs7.getInt("count(pname)");
       a7.setText(""+R);
        }
        String str8="select count(pname) from players where pname='OUSAMANNE DEMBELE'";
            
             ResultSet rs8=stmt.executeQuery(str8);
             if(rs8.next())
       {
       int R=rs8.getInt("count(pname)");
       a8.setText(""+R);
        }     
       String str9="select count(pname) from players where pname='NETO'";
            
             ResultSet rs9=stmt.executeQuery(str9);
             if(rs9.next())
       {
       int R=rs9.getInt("count(pname)");
       a9.setText(""+R);
        }
      String str10="select count(pname) from players where pname='CLEMET LENGLET'";
            
             ResultSet rs10=stmt.executeQuery(str10);
             if(rs10.next())
       {
       int R=rs10.getInt("count(pname)");
       a10.setText(""+R);
        }
       
        String str11="select count(pname) from players where pname='ANTOINE GRIEZMAN'";
            
             ResultSet rs11=stmt.executeQuery(str11);
             if(rs11.next())
       {
       int R=rs11.getInt("count(pname)");
       a11.setText(""+R);
        }
             String str12="select count(pname) from players where pname='JORDI ALBA'";
            
             ResultSet rs12=stmt.executeQuery(str12);
             if(rs12.next())
       {
       int R=rs12.getInt("count(pname)");
       a12.setText(""+R);
        }
             String str13="select count(pname) from players where pname='SERGIO ROBERTO'";
            
             ResultSet rs13=stmt.executeQuery(str13);
             if(rs13.next())
       {
       int R=rs13.getInt("count(pname)");
       a13.setText(""+R);
        }
             String str14="select count(pname) from players where pname='FRENKIE DE JONG'";
            
             ResultSet rs14=stmt.executeQuery(str14);
             if(rs14.next())
       {
       int R=rs14.getInt("count(pname)");
       a14.setText(""+R);
        }
             String str15="select count(pname) from players where pname='ARTURO VIDAL'";
            
             ResultSet rs15=stmt.executeQuery(str15);
             if(rs15.next())
       {
       int R=rs15.getInt("count(pname)");
       a15.setText(""+R);
        }
               String str21="select count(pname) from players where pname='KEYLOR NAVAS'";
            
             ResultSet rs21=stmt.executeQuery(str21);
             if(rs21.next())
       {
       int R=rs21.getInt("count(pname)");
       b1.setText(""+R);
        }
         String str22="select count(pname) from players where pname='DANI CARVAJAL'";
             ResultSet rs22=stmt.executeQuery(str22);
             if(rs22.next())
       {
       int R=rs22.getInt("count(pname)");
       b2.setText(""+R);
        } 
        String str23="select count(pname) from players where pname='SERGIO RAMOS'";
             ResultSet rs23=stmt.executeQuery(str23);
             if(rs23.next())
       {
       int R=rs23.getInt("count(pname)");
       b3.setText(""+R);
        }  
             String str24="select count(pname) from players where pname='RAPHAEL VARANE'";
             ResultSet rs24=stmt.executeQuery(str24);
             if(rs24.next())
       {
       int R=rs24.getInt("count(pname)");
       b4.setText(""+R);
        } 
             String str25="select count(pname) from players where pname='KARIM BENZEMA'";
             ResultSet rs25=stmt.executeQuery(str25);
             if(rs25.next())
       {
       int R=rs25.getInt("count(pname)");
       b5.setText(""+R);
        }
             String str26="select count(pname) from players where pname='TONI KROOS'";
             ResultSet rs26=stmt.executeQuery(str26);
             if(rs26.next())
       {
       int R=rs26.getInt("count(pname)");
       b6.setText(""+R);
        } 
             String str27="select count(pname) from players where pname='LUKA MODRIC'";
             ResultSet rs27=stmt.executeQuery(str27);
             if(rs27.next())
       {
       int R=rs27.getInt("count(pname)");
       b7.setText(""+R);
        } 
             String str28="select count(pname) from players where pname='GARETH BALE'";
             ResultSet rs28=stmt.executeQuery(str28);
             if(rs28.next())
       {
       int R=rs28.getInt("count(pname)");
       b8.setText(""+R);
        } 
             String str29="select count(pname) from players where pname='MARCELO VIERRA'";
             ResultSet rs29=stmt.executeQuery(str29);
             if(rs29.next())
       {
       int R=rs29.getInt("count(pname)");
       b9.setText(""+R);
        } 
             String str210="select count(pname) from players where pname='THIBAUT COURTOIS'";
             ResultSet rs210=stmt.executeQuery(str210);
             if(rs210.next())
       {
       int R=rs210.getInt("count(pname)");
       b10.setText(""+R);
        } 
             String str211="select count(pname) from players where pname='LUCAS VAZQUEZ'";
             ResultSet rs211=stmt.executeQuery(str211);
             if(rs211.next())
       {
       int R=rs211.getInt("count(pname)");
       b11.setText(""+R);
        } 
             String str212="select count(pname) from players where pname='LUKA JOVIC'";
             ResultSet rs212=stmt.executeQuery(str212);
             if(rs212.next())
       {
       int R=rs212.getInt("count(pname)");
       b12.setText(""+R);
        } 
             String str213="select count(pname) from players where pname='MARCO ASENSIO'";
             ResultSet rs213=stmt.executeQuery(str213);
             if(rs213.next())
       {
       int R=rs213.getInt("count(pname)");
       b13.setText(""+R);
        } 
             String str214="select count(pname) from players where pname='VINICIUS JUNIOR'";
             ResultSet rs214=stmt.executeQuery(str214);
             if(rs214.next())
       {
       int R=rs214.getInt("count(pname)");
       b14.setText(""+R);
        } 
             String str215="select count(pname) from players where pname='EDEN HAZARD'";
             ResultSet rs215=stmt.executeQuery(str215);
             if(rs215.next())
       {
       int R=rs215.getInt("count(pname)");
       b15.setText(""+R);
        }
                String str31="select count(pname) from players where pname='ANTONIO ADAN'";
            
             ResultSet rs31=stmt.executeQuery(str31);
             if(rs31.next())
       {
       int R=rs31.getInt("count(pname)");
       c1.setText(""+R);
        }
                String str32="select count(pname) from players where pname='THOMAS PARTEY'";
            
             ResultSet rs32=stmt.executeQuery(str32);
             if(rs32.next())
       {
       int R=rs32.getInt("count(pname)");
       c2.setText(""+R);
        }
              String str33="select count(pname) from players where pname='JOAO FELIX'";
            
             ResultSet rs33=stmt.executeQuery(str33);
             if(rs33.next())
       {
       int R=rs33.getInt("count(pname)");
       c3.setText(""+R);
        }
              String str34="select count(pname) from players where pname='SAUL NIGUEZ'";
            
             ResultSet rs34=stmt.executeQuery(str34);
             if(rs34.next())
       {
       int R=rs34.getInt("count(pname)");
       c4.setText(""+R);
        }
              String str35="select count(pname) from players where pname='ALVARO MORATA'";
            
             ResultSet rs35=stmt.executeQuery(str35);
             if(rs35.next())
       {
       int R=rs35.getInt("count(pname)");
       c5.setText(""+R);
        }
              String str36="select count(pname) from players where pname='ANGEL CORREA'";
            
             ResultSet rs36=stmt.executeQuery(str36);
             if(rs36.next())
       {
       int R=rs36.getInt("count(pname)");
       c6.setText(""+R);
        }
              String str37="select count(pname) from players where pname='THOMAS LEMAR'";
            
             ResultSet rs37=stmt.executeQuery(str37);
             if(rs37.next())
       {
       int R=rs37.getInt("count(pname)");
       c7.setText(""+R);
        }
              String str38="select count(pname) from players where pname='RENAN LODI'";
            
             ResultSet rs38=stmt.executeQuery(str38);
             if(rs38.next())
       {
       int R=rs38.getInt("count(pname)");
       c8.setText(""+R);
        }
             String str39="select count(pname) from players where pname='JAN OBLAK'";
             ResultSet rs39=stmt.executeQuery(str39);
             if(rs39.next())
       {
       int R=rs39.getInt("count(pname)");
       c9.setText(""+R);
        } 
             String str310="select count(pname) from players where pname='MARCOS LLORENTE'";
             ResultSet rs310=stmt.executeQuery(str310);
             if(rs310.next())
       {
       int R=rs310.getInt("count(pname)");
       c10.setText(""+R);
        } 
             String str311="select count(pname) from players where pname='KOKE'";
             ResultSet rs311=stmt.executeQuery(str311);
             if(rs311.next())
       {
       int R=rs311.getInt("count(pname)");
       c11.setText(""+R);
        } 
             String str312="select count(pname) from players where pname='DIEGO COSTA'";
             ResultSet rs312=stmt.executeQuery(str312);
             if(rs312.next())
       {
       int R=rs312.getInt("count(pname)");
       c12.setText(""+R);
        } 
             String str313="select count(pname) from players where pname='VITOLO'";
             ResultSet rs313=stmt.executeQuery(str313);
             if(rs313.next())
       {
       int R=rs313.getInt("count(pname)");
       c13.setText(""+R);
        } 
             String str314="select count(pname) from players where pname='MARIO HERMOSO'";
             ResultSet rs314=stmt.executeQuery(str314);
             if(rs314.next())
       {
       int R=rs314.getInt("count(pname)");
       c14.setText(""+R);
        } 
             String str315="select count(pname) from players where pname='KIERAN TRIPPIER'";
             ResultSet rs315=stmt.executeQuery(str315);
             if(rs315.next())
       {
       int R=rs315.getInt("count(pname)");
       c15.setText(""+R);
        }
               String str41="select count(pname) from players where pname='TOMAS VACILIK'";
            
             ResultSet rs41=stmt.executeQuery(str41);
             if(rs41.next())
       {
       int R=rs41.getInt("count(pname)");
       d1.setText(""+R);
        }
                String str42="select count(pname) from players where pname='SERGI GOMEZ'";
            
             ResultSet rs42=stmt.executeQuery(str42);
             if(rs42.next())
       {
       int R=rs42.getInt("count(pname)");
       d2.setText(""+R);
        }
              String str43="select count(pname) from players where pname='SIMON KJAER'";
            
             ResultSet rs43=stmt.executeQuery(str43);
             if(rs43.next())
       {
       int R=rs43.getInt("count(pname)");
       d3.setText(""+R);
        }
              String str44="select count(pname) from players where pname='IBRAHIM AMADOU'";
            
             ResultSet rs44=stmt.executeQuery(str44);
             if(rs44.next())
       {
       int R=rs44.getInt("count(pname)");
       d4.setText(""+R);
        }
              String str45="select count(pname) from players where pname='DANIEL CARRICO'";
            
             ResultSet rs45=stmt.executeQuery(str45);
             if(rs45.next())
       {
       int R=rs45.getInt("count(pname)");
       d5.setText(""+R);
        }
              String str46="select count(pname) from players where pname='EVER BANEGA'";
            
             ResultSet rs46=stmt.executeQuery(str46);
             if(rs46.next())
       {
       int R=rs46.getInt("count(pname)");
       d6.setText(""+R);
        }
              String str47="select count(pname) from players where pname='ALEIX VIDAL'";
            
             ResultSet rs47=stmt.executeQuery(str47);
             if(rs47.next())
       {
       int R=rs47.getInt("count(pname)");
       d7.setText(""+R);
        }
              String str48="select count(pname) from players where pname='ANDRE SILVA'";
            
             ResultSet rs48=stmt.executeQuery(str48);
             if(rs48.next())
       {
       int R=rs48.getInt("count(pname)");
       d8.setText(""+R);
        }
             String str49="select count(pname) from players where pname='NOLITO'";
             ResultSet rs49=stmt.executeQuery(str49);
             if(rs49.next())
       {
       int R=rs49.getInt("count(pname)");
       d9.setText(""+R);
        } 
             String str410="select count(pname) from players where pname='JESUS NAVAS'";
             ResultSet rs410=stmt.executeQuery(str410);
             if(rs410.next())
       {
       int R=rs410.getInt("count(pname)");
       d10.setText(""+R);
        } 
             String str411="select count(pname) from players where pname='JUAN SORIANO'";
             ResultSet rs411=stmt.executeQuery(str411);
             if(rs411.next())
       {
       int R=rs411.getInt("count(pname)");
       d11.setText(""+R);
        } 
             String str412="select count(pname) from players where pname='ESCUDERO'";
             ResultSet rs412=stmt.executeQuery(str412);
             if(rs412.next())
       {
       int R=rs412.getInt("count(pname)");
       d12.setText(""+R);
        } 
             String str413="select count(pname) from players where pname='ROQUE MESA '";
             ResultSet rs413=stmt.executeQuery(str413);
             if(rs413.next())
       {
       int R=rs413.getInt("count(pname)");
       d13.setText(""+R);
        } 
             String str414="select count(pname) from players where pname='QUINCY PROMES'";
             ResultSet rs414=stmt.executeQuery(str414);
             if(rs414.next())
       {
       int R=rs414.getInt("count(pname)");
       d14.setText(""+R);
        } 
             String str415="select count(pname) from players where pname='BEN YEDDER'";
             ResultSet rs415=stmt.executeQuery(str415);
             if(rs415.next())
       {
       int R=rs415.getInt("count(pname)");
       d15.setText(""+R);
        }
              String str51="select count(pname) from players where pname='JAUME DOMENECH'";
            
             ResultSet rs51=stmt.executeQuery(str51);
             if(rs51.next())
       {
       int R=rs51.getInt("count(pname)");
       e1.setText(""+R);
        }
                String str52="select count(pname) from players where pname='JASPER CILLESSEN'";
            
             ResultSet rs52=stmt.executeQuery(str52);
             if(rs52.next())
       {
       int R=rs52.getInt("count(pname)");
       e2.setText(""+R);
        }
              String str53="select count(pname) from players where pname='GABRIEL PAULISTA'";
            
             ResultSet rs53=stmt.executeQuery(str53);
             if(rs53.next())
       {
       int R=rs53.getInt("count(pname)");
       e3.setText(""+R);
        }
              String str54="select count(pname) from players where pname='SALVA RUIZ'";
            
             ResultSet rs54=stmt.executeQuery(str54);
             if(rs54.next())
       {
       int R=rs54.getInt("count(pname)");
       e4.setText(""+R);
        }
              String str55="select count(pname) from players where pname='JOSE GAYA'";
            
             ResultSet rs55=stmt.executeQuery(str55);
             if(rs55.next())
       {
       int R=rs55.getInt("count(pname)");
       e5.setText(""+R);
        }
              String str56="select count(pname) from players where pname='DANIEL WASS'";
            
             ResultSet rs56=stmt.executeQuery(str56);
             if(rs56.next())
       {
       int R=rs56.getInt("count(pname)");
       e6.setText(""+R);
        }
              String str57="select count(pname) from players where pname='DANIEL PAREJO'";
            
             ResultSet rs57=stmt.executeQuery(str57);
             if(rs57.next())
       {
       int R=rs57.getInt("count(pname)");
       e7.setText(""+R);
        }
              String str58="select count(pname) from players where pname='CARLOS SOLER'";
            
             ResultSet rs58=stmt.executeQuery(str58);
             if(rs58.next())
       {
       int R=rs58.getInt("count(pname)");
       e8.setText(""+R);
        }
             String str59="select count(pname) from players where pname='GONCALO GUEDES'";
             ResultSet rs59=stmt.executeQuery(str59);
             if(rs59.next())
       {
       int R=rs59.getInt("count(pname)");
       e9.setText(""+R);
        } 
             String str510="select count(pname) from players where pname='ALVARO MEDRAN'";
             ResultSet rs510=stmt.executeQuery(str510);
             if(rs510.next())
       {
       int R=rs510.getInt("count(pname)");
       e10.setText(""+R);
        } 
             String str511="select count(pname) from players where pname='RODRIGO'";
             ResultSet rs511=stmt.executeQuery(str511);
             if(rs511.next())
       {
       int R=rs511.getInt("count(pname)");
       e11.setText(""+R);
        } 
             String str512="select count(pname) from players where pname='MAXI GOMEZ'";
             ResultSet rs512=stmt.executeQuery(str512);
             if(rs512.next())
       {
       int R=rs512.getInt("count(pname)");
       e12.setText(""+R);
        } 
             String str513="select count(pname) from players where pname='KEVIN GAMEIRO '";
             ResultSet rs513=stmt.executeQuery(str513);
             if(rs513.next())
       {
       int R=rs513.getInt("count(pname)");
       e13.setText(""+R);
        } 
             String str514="select count(pname) from players where pname='FERRAN TORRES'";
             ResultSet rs514=stmt.executeQuery(str514);
             if(rs514.next())
       {
       int R=rs514.getInt("count(pname)");
       e14.setText(""+R);
        } 
             String str515="select count(pname) from players where pname='LEE KANG-IN'";
             ResultSet rs515=stmt.executeQuery(str515);
             if(rs515.next())
       {
       int R=rs515.getInt("count(pname)");
       e15.setText(""+R);
        }
        }  catch(Exception e)
        {
              JOptionPane.showMessageDialog(null, e);  
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(goalscorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(goalscorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(goalscorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(goalscorer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new goalscorer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a14;
    private javax.swing.JTextField a15;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b10;
    private javax.swing.JTextField b11;
    private javax.swing.JTextField b12;
    private javax.swing.JTextField b13;
    private javax.swing.JTextField b14;
    private javax.swing.JTextField b15;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JTextField b5;
    private javax.swing.JTextField b6;
    private javax.swing.JTextField b7;
    private javax.swing.JTextField b8;
    private javax.swing.JTextField b9;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c10;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JTextField c13;
    private javax.swing.JTextField c14;
    private javax.swing.JTextField c15;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JTextField c5;
    private javax.swing.JTextField c6;
    private javax.swing.JTextField c7;
    private javax.swing.JTextField c8;
    private javax.swing.JTextField c9;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d10;
    private javax.swing.JTextField d11;
    private javax.swing.JTextField d12;
    private javax.swing.JTextField d13;
    private javax.swing.JTextField d14;
    private javax.swing.JTextField d15;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JTextField d4;
    private javax.swing.JTextField d5;
    private javax.swing.JTextField d6;
    private javax.swing.JTextField d7;
    private javax.swing.JTextField d8;
    private javax.swing.JTextField d9;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e10;
    private javax.swing.JTextField e11;
    private javax.swing.JTextField e12;
    private javax.swing.JTextField e13;
    private javax.swing.JTextField e14;
    private javax.swing.JTextField e15;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private javax.swing.JTextField e7;
    private javax.swing.JTextField e8;
    private javax.swing.JTextField e9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
