package soura;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author L41
 */
public class points extends javax.swing.JFrame {

    /**
     * Creates new form points
     */
    public points() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        g1 = new javax.swing.JTextField();
        w1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        g2 = new javax.swing.JTextField();
        w2 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        l2 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        g3 = new javax.swing.JTextField();
        w3 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        l3 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        g4 = new javax.swing.JTextField();
        w4 = new javax.swing.JTextField();
        d4 = new javax.swing.JTextField();
        l4 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        g5 = new javax.swing.JTextField();
        w5 = new javax.swing.JTextField();
        d5 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        l5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("FC Barcelona");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Real Madrid C.F.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Atletico Madrid");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Valencia CF");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Sevilla FC");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("total match");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("wins");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Draws");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("loses");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("points");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        g1.setEditable(false);
        getContentPane().add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 37, -1));

        w1.setEditable(false);
        getContentPane().add(w1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 37, -1));

        d1.setEditable(false);
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 37, -1));

        l1.setEditable(false);
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 37, -1));

        p1.setEditable(false);
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 37, -1));

        g2.setEditable(false);
        getContentPane().add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 37, -1));

        w2.setEditable(false);
        getContentPane().add(w2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 37, -1));

        d2.setEditable(false);
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 37, -1));

        l2.setEditable(false);
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 37, -1));

        p2.setEditable(false);
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 37, -1));

        g3.setEditable(false);
        getContentPane().add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 37, -1));

        w3.setEditable(false);
        getContentPane().add(w3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 37, -1));

        d3.setEditable(false);
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 37, -1));

        l3.setEditable(false);
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 37, -1));

        p3.setEditable(false);
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 37, -1));

        g4.setEditable(false);
        getContentPane().add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 37, -1));

        w4.setEditable(false);
        getContentPane().add(w4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 37, -1));

        d4.setEditable(false);
        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 37, -1));

        l4.setEditable(false);
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 37, -1));

        p4.setEditable(false);
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 37, -1));

        g5.setEditable(false);
        getContentPane().add(g5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 37, -1));

        w5.setEditable(false);
        getContentPane().add(w5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 37, -1));

        d5.setEditable(false);
        getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 37, -1));

        p5.setEditable(false);
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 37, -1));

        l5.setEditable(false);
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 37, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soura/images12.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 570, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {
             Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project12","root","123456");
            Statement stmt=con.createStatement();
             String str="select count(tname) from win where tname='FC Barcelona' ";
            
             ResultSet rs=stmt.executeQuery(str);
             if(rs.next())
       {
       int R=rs.getInt("count(tname)");
       w1.setText(""+R);
       }
              String str2="select count(tname) from draw where tname='FC Barcelona' ";
                ResultSet rs2=stmt.executeQuery(str2);
                   if(rs2.next())
       {
       int S=rs2.getInt("count(tname)");
       d1.setText(""+S);
       }
                    String str3="select count(tname) from loss where tname='FC Barcelona' ";
                ResultSet rs3=stmt.executeQuery(str3);
                   if(rs3.next())
       {
       int S1=rs3.getInt("count(tname)");
       l1.setText(""+S1);
       }
                   
                   
                   
                   
                     String str4="select count(tname) from win where tname='Real Madrid C.F.' ";
            
             ResultSet rsr=stmt.executeQuery(str4);
             if(rsr.next())
       {
       int R=rsr.getInt("count(tname)");
       w2.setText(""+R);
       }
              String str24="select count(tname) from draw where tname='Real Madrid C.F.' ";
                ResultSet rs23=stmt.executeQuery(str24);
                   if(rs23.next())
       {
       int S=rs23.getInt("count(tname)");
       d2.setText(""+S);
       }
                    String str34="select count(tname) from loss where tname='Real Madrid C.F.' ";
                ResultSet rs34=stmt.executeQuery(str34);
                   if(rs34.next())
       {
       int S1=rs34.getInt("count(tname)");
       l2.setText(""+S1);
       }
                   
                   
                   
                   
                   
                             
                     String str45="select count(tname) from win where tname='Atletico Madrid' ";
            
             ResultSet rsrp=stmt.executeQuery(str45);
             if(rsrp.next())
       {
       int R=rsrp.getInt("count(tname)");
       w3.setText(""+R);
       }
              String str241="select count(tname) from draw where tname='Atletico Madrid' ";
                ResultSet rs231=stmt.executeQuery(str241);
                   if(rs231.next())
       {
       int S=rs231.getInt("count(tname)");
       d3.setText(""+S);
       }
                    String str343="select count(tname) from loss where tname='Atletico Madrid' ";
                ResultSet rs343=stmt.executeQuery(str343);
                   if(rs343.next())
       {
       int S1=rs343.getInt("count(tname)");
       l3.setText(""+S1);
       }
             
                   
                   
                                          
                     String str456="select count(tname) from win where tname='Sevilla FC' ";
            
             ResultSet rsrp6=stmt.executeQuery(str456);
             if(rsrp6.next())
       {
       int R=rsrp6.getInt("count(tname)");
       w4.setText(""+R);
       }
              String str2416="select count(tname) from draw where tname='Sevilla FC' ";
                ResultSet rs2316=stmt.executeQuery(str2416);
                   if(rs2316.next())
       {
       int S=rs2316.getInt("count(tname)");
       d4.setText(""+S);
       }
                    String str3436="select count(tname) from loss where tname='Sevilla FC' ";
                ResultSet rs3436=stmt.executeQuery(str3436);
                   if(rs3436.next())
       {
       int S1=rs3436.getInt("count(tname)");
       l4.setText(""+S1);
       }
                   
                   
                   
                   
                   
                   
                             String str4567="select count(tname) from win where tname='Sevilla FC' ";
            
             ResultSet rsrp67=stmt.executeQuery(str4567);
             if(rsrp67.next())
       {
       int R=rsrp67.getInt("count(tname)");
       w5.setText(""+R);
       }
              String str24167="select count(tname) from draw where tname='Sevilla FC' ";
                ResultSet rs23167=stmt.executeQuery(str24167);
                   if(rs23167.next())
       {
       int S=rs23167.getInt("count(tname)");
       d5.setText(""+S);
       }
                    String str34367="select count(tname) from loss where tname='Sevilla FC' ";
                ResultSet rs34367=stmt.executeQuery(str34367);
                   if(rs34367.next())
       {
       int S1=rs34367.getInt("count(tname)");
       l5.setText(""+S1);
       }
                   
                   
                   int a=Integer.parseInt(w1.getText());
                   int b=Integer.parseInt(d1.getText());
                   int c=Integer.parseInt(l1.getText());
                   int po;
                   po=(3*a)+(b);
                   int gp=a+b+c;
                   g1.setText(""+gp);
                  p1.setText(""+po);
                   
                   int a2=Integer.parseInt(w2.getText());
                   int b2=Integer.parseInt(d2.getText());
                   int c2=Integer.parseInt(l2.getText());
                   int po2;
                   po2=(3*a2)+(b2);
                   int gp2=a2+b2+c2;
                   g2.setText(""+gp2);
                  p2.setText(""+po2); 
                   
                   int a3=Integer.parseInt(w3.getText());
                   int b3=Integer.parseInt(d3.getText());
                   int c3=Integer.parseInt(l3.getText());
                   int po3;
                   po3=(3*a3)+(b3);
                   int gp3=a3+b3+c3;
                   g3.setText(""+gp3);
                   p3.setText(""+po3);
                   
int a4=Integer.parseInt(w4.getText());
                   int b4=Integer.parseInt(d4.getText());
                   int c4=Integer.parseInt(l4.getText());
                   int po4;
                   po4=(3*a4)+(b4);
                   int gp4=a4+b4+c4;
                   g4.setText(""+gp4);
                        p4.setText(""+po4);              


int a5=Integer.parseInt(w5.getText());
                   int b5=Integer.parseInt(d5.getText());
                   int c5=Integer.parseInt(l5.getText());
                   int po5;
                   po5=(3*a5)+(b5);
                   int gp5=a5+b5+c5;
                   g5.setText(""+gp5);
                             p5.setText(""+po5);         
                   
             
                   
                   
                   
                   
                   
                   
            
        }catch(Exception e)
        {
              JOptionPane.showMessageDialog(null, e);  
        }
        
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       startframe newfr2 =new startframe();
    newfr2.setVisible(true);    
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(points.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new points().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JTextField d4;
    private javax.swing.JTextField d5;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField g4;
    private javax.swing.JTextField g5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField l1;
    private javax.swing.JTextField l2;
    private javax.swing.JTextField l3;
    private javax.swing.JTextField l4;
    private javax.swing.JTextField l5;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField w1;
    private javax.swing.JTextField w2;
    private javax.swing.JTextField w3;
    private javax.swing.JTextField w4;
    private javax.swing.JTextField w5;
    // End of variables declaration//GEN-END:variables
}
