package soura;

import soura.startframe;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.*;
import soura.sbfinal;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SC
 */
public class tselect extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public tselect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        teama = new javax.swing.JComboBox<>();
        teamb = new javax.swing.JComboBox<>();
        image1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JList<>();
        image2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        teama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT TEAM 1---", "FC Barcelona", "Real Madrid C.F.", "Atletico Madrid", "Valencia CF", "Sevilla FC", " " }));
        teama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                teamaItemStateChanged(evt);
            }
        });
        teama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamaActionPerformed(evt);
            }
        });
        getContentPane().add(teama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        teamb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT TEAM 2---", "FC Barcelona", "Real Madrid C.F.", "Atletico Madrid", "Valencia CF", "Sevilla FC", " " }));
        teamb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                teambItemStateChanged(evt);
            }
        });
        getContentPane().add(teamb, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));
        getContentPane().add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 42, 198, 140));

        ta.setBorder(javax.swing.BorderFactory.createTitledBorder("PLAYING 15"));
        ta.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                taValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 211, 272, 345));

        tb.setBorder(javax.swing.BorderFactory.createTitledBorder("PLAYING 15"));
        jScrollPane2.setViewportView(tb);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 279, 345));
        getContentPane().add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 182, 135));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soura/download.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_teamaItemStateChanged
        String A=teama.getSelectedItem().toString();
        DefaultListModel a=new DefaultListModel();
        if(A.equals("---SELECT TEAM 1---"))
        {
            image1.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\logo.png"));
            a.addElement("SELECT TEAM");
            ta.setModel(a);
            ta.clearSelection();
        }
        else if(A.equals("FC Barcelona"))
        {
            image1.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\barcalogo.png"));
            
            a.addElement("MARC ANDRE TER STEGEN");
            a.addElement("GERRAD PIQUE");
            a.addElement("IVAN RAKITIC");
            a.addElement("SERGIO BUSQUETS");
            a.addElement("ARTHUR MELO");
            a.addElement("LUIS SUAREZ");
            a.addElement("LIONEL MESSI ");
            a.addElement("OUSAMANNE DEMBELE");
            a.addElement("NETO ");
            a.addElement("CLEMET LENGLET");
            a.addElement("ANTOINE GRIEZMAN");
            a.addElement("JORDI ALBA ");
            a.addElement("SERGIO ROBERTO");
            a.addElement("FRENKIE DE JONG");
            a.addElement("ARTURO VIDAL");
            ta.setModel(a);
            ta.clearSelection();
           
        }
        else if (A.equals("Real Madrid C.F."))
        {
            image1.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\rmdlogo.png"));
         
            a.addElement("KEYLOR NAVAS");
            a.addElement("DANI CARVAJAL");
            a.addElement("SERGIO RAMOS ");
            a.addElement("RAPHAEL VARANE");
            a.addElement("KARIM BENZEMA ");
            a.addElement("TONI KROOS");
            a.addElement("LUKA MODRIC");
            a.addElement("GARETH BALE");
            a.addElement("MARCELO VIERRA");
            a.addElement("THIBAUT COURTOIS");
            a.addElement("LUCAS VAZQUEZ");
            a.addElement("LUKA JOVIC");
             a.addElement("MARCO ASENSIO");
            a.addElement("VINICIUS JUNIOR");
            a.addElement("EDEN HAZARD");
            ta.setModel(a);
            ta.clearSelection();
        }
        else if(A.equals("Atletico Madrid"))
        {
            image1.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\atmlogo.png"));
   
            a.addElement("ANTONIO ADAN");
            a.addElement("THOMAS PARTEY");
            a.addElement("KOKE");
            a.addElement("JOAO FELIX ");
            a.addElement("SAUL NIGUEZ");
            a.addElement("ALVARO MORATA");
            a.addElement("ANGEL CORREA");
            a.addElement("THOMAS LEMAR");
            a.addElement("RENAN LODI ");
            a.addElement("JAN OBLAK");
            a.addElement("MARCOS LLORENTE");
            a.addElement("DIEGO COSTA");
            a.addElement("VITOLO");
            a.addElement("MARIO HERMOSO");
            a.addElement("KIERAN TRIPPIER");
            ta.setModel(a);
            ta.clearSelection();
        }else if (A.equals("Sevilla FC"))
        {
            image1.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\sevillalogo.png"));
            
            a.addElement("TOMAS VACILIK");
            a.addElement("SERGI GOMEZ");
            a.addElement("SIMON KJAER");
            a.addElement("IBRAHIM AMADOU");
            a.addElement("DANIEL CARRICO ");
            a.addElement("EVER BANEGA ");
            a.addElement("ALEIX VIDAL");
            a.addElement("ANDRE SILVA");
            a.addElement("NOLITO");
            a.addElement("JESUS NAVAS" );
            a.addElement("JUAN SORIANO");
            a.addElement("ESCUDERO");
            a.addElement("ROQUE MESA ");
            a.addElement("QUINCY PROMES");
            a.addElement("BEN YEDDER");
            ta.setModel(a);
            ta.clearSelection();      
         }else if(A.equals("Valencia CF"))
         {
             image1.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\valencialogo.png"));

           a.addElement("JAUME DOMENECH") ;
           a.addElement("JASPER CILLESSEN");
           a.addElement("GABRIEL PAULISTA");
           a.addElement("SALVA RUIZ");
           a.addElement("JOSE GAYA");
           a.addElement("DANIEL WASS");
           a.addElement("DANIEL PAREJO");
           a.addElement("CARLOS SOLER");
           a.addElement("GONCALO GUEDES");
           a.addElement("ALVARO MEDRAN");
           a.addElement("RODRIGO");
           a.addElement("MAXI GOMEZ");
           a.addElement("KEVIN GAMEIRO");
           a.addElement("FERRAN TORRES"); 
           a.addElement("LEE KANG-IN"); 
           ta.setModel(a);
            ta.clearSelection(); 
         }
    }//GEN-LAST:event_teamaItemStateChanged

    private void teambItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_teambItemStateChanged
     String A=teamb.getSelectedItem().toString();
        DefaultListModel a=new DefaultListModel();
        if(A.equals("---SELECT TEAM 2---"))
        {
            image2.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\logo.png"));
            a.addElement("SELECT TEAM");
            tb.setModel(a);
            tb.clearSelection();
        }
        else if(A.equals("FC Barcelona"))
        {
            image2.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\barcalogo.png"));
    
            a.addElement("MARC ANDRE TER STEGEN");
            a.addElement("GERRAD PIQUE");
            a.addElement("IVAN RAKITIC");
            a.addElement("SERGIO BUSQUETS");
            a.addElement("ARTHUR MELO");
            a.addElement("LUIS SUAREZ");
            a.addElement("LIONEL MESSI ");
            a.addElement("OUSAMANNE DEMBELE");
            a.addElement("NETO ");
            a.addElement("CLEMET LENGLET");
            a.addElement("ANTOINE GRIEZMAN");
            a.addElement("JORDI ALBA ");
            a.addElement("SERGIO ROBERTO");
            a.addElement("FRENKIE DE JONG");
            a.addElement("ARTURO VIDAL");
            tb.setModel(a);
            tb.clearSelection();
        }
        else if (A.equals("Real Madrid C.F."))
        {
            image2.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\rmdlogo.png"));

            a.addElement("KEYLOR NAVAS");
            a.addElement("DANI CARVAJAL");
            a.addElement("SERGIO RAMOS ");
            a.addElement("RAPHAEL VARANE");
            a.addElement("KARIM BENZEMA ");
            a.addElement("TONI KROOS");
            a.addElement("LUKA MODRIC");
            a.addElement("GARETH BALE");
            a.addElement("MARCELO VIERRA");
            a.addElement("THIBAUT COURTOIS");
            a.addElement("LUCAS VAZQUEZ");
            a.addElement("LUKA JOVIC");
             a.addElement("MARCO ASENSIO");
            a.addElement("VINICIUS JUNIOR");
            a.addElement("EDEN HAZARD");            
            tb.setModel(a);
            tb.clearSelection();
        }
        else if(A.equals("Atletico Madrid"))
        {
            image2.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\atmlogo.png"));
     
            a.addElement("ANTONIO ADAN");
            a.addElement("THOMAS PARTEY");
            a.addElement("KOKE");
            a.addElement("JOAO FELIX ");
            a.addElement("SAUL NIGUEZ");
            a.addElement("ALVARO MORATA");
            a.addElement("ANGEL CORREA");
            a.addElement("THOMAS LEMAR");
            a.addElement("RENAN LODI ");
            a.addElement("JAN OBLAK");
            a.addElement("MARCOS LLORENTE");
            a.addElement("DIEGO COSTA");
            a.addElement("VITOLO");
            a.addElement("MARIO HERMOSO");
            a.addElement("KIERAN TRIPPIER");
            tb.setModel(a);
            tb.clearSelection();
        }else if (A.equals("Sevilla FC"))
        {
            image2.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\sevillalogo.png"));
         
            a.addElement("TOMAS VACILIK");
            a.addElement("SERGI GOMEZ");
            a.addElement("SIMON KJAER");
            a.addElement("IBRAHIM AMADOU");
            a.addElement("DANIEL CARRICO ");
            a.addElement("EVER BANEGA ");
            a.addElement("ALEIX VIDAL");
            a.addElement("ANDRE SILVA");
            a.addElement("NOLITO");
            a.addElement("JESUS NAVAS" );
            a.addElement("JUAN SORIANO");
            a.addElement("ESCUDERO");
            a.addElement("ROQUE MESA ");
            a.addElement("QUINCY PROMES");
            a.addElement("BEN YEDDER");
            tb.setModel(a);
            tb.clearSelection();      
         }else if(A.equals("Valencia CF"))
         {
             image2.setIcon(new ImageIcon("D:\\2018-19\\IP Practical\\shirsh\\src\\soura\\valencialogo.png"));
              
           a.addElement("JAUME DOMENECH") ;
           a.addElement("JASPER CILLESSEN");
           a.addElement("GABRIEL PAULISTA");
           a.addElement("SALVA RUIZ");
           a.addElement("JOSE GAYA");
           a.addElement("DANIEL WASS");
           a.addElement("DANIEL PAREJO");
           a.addElement("CARLOS SOLER");
           a.addElement("GONCALO GUEDES");
           a.addElement("ALVARO MEDRAN");
           a.addElement("RODRIGO");
           a.addElement("MAXI GOMEZ");
           a.addElement("KEVIN GAMEIRO");
           a.addElement("FERRAN TORRES"); 
           a.addElement("LEE KANG-IN");
           tb.setModel(a);
            tb.clearSelection(); 
         }    // TODO add your handling code here:
    }//GEN-LAST:event_teambItemStateChanged

    private void taValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_taValueChanged
        // TODO add your handling code here:
     
        
          
        
         
             
           
        
                  
      
      
      
      
    }//GEN-LAST:event_taValueChanged

    private void teamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  try{ 
        Thread.sleep(150);        
        JOptionPane.showMessageDialog(null,"select 11 players");        
}catch (Exception e)
{
      
}
         
   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
startframe newfra2 =new startframe();
    newfra2.setVisible(true);    
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int res=JOptionPane.showConfirmDialog(null,"DO U WANT TO CONTINUE?");
        String q=teama.getSelectedItem().toString();
        String p=teamb.getSelectedItem().toString();

        if (q.equals(p))
        JOptionPane.showMessageDialog(null,"PLEASE SELECT TWO DIFFERENT TEAMS");
        else if(res==0){
            List<String> tableone=ta.getSelectedValuesList();
            List<String> tabletwo=tb.getSelectedValuesList();

            int sizea=tableone.size();
            int sizeb=tabletwo.size();
            if((sizea==11)&&(sizeb==11)){
                try{
                    Thread.sleep(1500);
                   

                }catch (Exception e)
                {

                }

                sbfinal newframe2 =new sbfinal(tableone,tabletwo,q,p);
                newframe2.setVisible(true);
                this.dispose();

            }
            else{
                JOptionPane.showMessageDialog(null,"PLEASE SELECT ELEVEN MEMBERS FROM EACH TEAM");
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tselect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JList<String> ta;
    public static javax.swing.JList<String> tb;
    private javax.swing.JComboBox<String> teama;
    private javax.swing.JComboBox<String> teamb;
    // End of variables declaration//GEN-END:variables
}
